### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by achimmihca** [erwindon/SaltGUI#381]
Installation Instructions

I had some trouble installing SaltGui.

I would had wished for the following information in your README.md
- The [saltgui](https://github.com/erwindon/SaltGUI/tree/master/saltgui) subfolder contains the webapp and contains all necessary files
- No DB setup or similar is required, because SaltGUI always fetches the data fresh from the salt-master via a REST API
- salt-api (command line tool for SaltStack) and CherryPy (HTTP server) are used to serve the REST API and SaltGUI itself
    - to install salt-api run `sudo apt install salt-api` (this is already in the README.md)
    - CherryPy does not need additional installation
    - The location of the saltgui folder on your system is not relevant. However, the path must be set in rest_cherrypy config to be serverd correctly.
        - The recommended path is `/srv/saltgui`
- Using the following config, SaltGUI will be served by CherryPy when accessing http://localhost:3333 in your browser:
```
rest_cherrypy:
  port: 3333
  host: localhost
  disable_ssl: true
  app: /srv/saltgui/index.html
  static: /srv/saltgui/static
  static_path: /static
```
        
Note that README.md already contains the rest_cherrypy config. But it was not clear to me that SaltGUI itself is served by rest_cherrypy. I tried to place SaltGUI files in `/var/www` to serve them using Apache, which did not work.

Would be nice if you can include it in the docs.

Thanks!
