### ISSUE TITLE
Missing hosts in job output in SaltGUI. Hosts are the on cli

### ISSUE THREAD

**Issue by xzenor** [erwindon/SaltGUI#389]
**Describe the bug**
The job output of one of my states is missing hosts. The output contains all hosts if I fetch the job output on the commandline but not in SaltGUI. It's not like there's a point where everything after that point is missing. There are hosts in the middle of the output on the cli that are missing in SaltGUI..
An extra weird thing is that after running the state the display hangs like it's still running with the form fields disabled for entry but it really is finished.
![Untitled](https://user-images.githubusercontent.com/15305998/137506654-9e07142f-3881-4897-9ed5-778c1a622af6.png)
As you can see, 8 responses but only 5 hosts are showing. jobs.lookup_jid on the cli shows all 8.

**To Reproduce**
Steps to reproduce the behaviour:
I just apply this state. It's nothing fancy actually.
```yaml
---
{% if grains['os'] == 'FreeBSD' %}
FreeBSD updates fetch:
  module.run:
    - name: freebsd_update.fetch
    - timeout: 90
    - splay: 15

FreeBSD updates install:
  module.run:
    - name: freebsd_update.install
    - timeout: 90
    - splay: 15
{% endif %}

Update packages refresh db:
  module.run:
    - name: pkg.refresh_db
    - timeout: 90
    - splay: 15

Update packages install updates:
  module.run:
    - name: pkg.upgrade
    - timeout: 90
    - splay: 15

{% if grains['os'] == 'FreeBSD' %}
autoremove unused dependencies:
  module.run:
    - name: pkg.autoremove
    - timeout: 90
    - splay: 15
{% endif %}
...
```

**Expected behaviour**
I expect all hosts to be shown like it does on the commandline. However, there's no error or anything with a hint of what's going wrong. 

**Additional context**
I've only noticed this with this one statefile. I cannot seem to reproduce this with other statefiles so it must be something specific in the output of the commands that I'm firing maybe in combination with the hostnames. If there's a way to enable a debug log somehow then I'd be happy to do that.
