### ISSUE TITLE
Authentication failed using PAM

### ISSUE THREAD

**Issue by mjoguinto** [erwindon/SaltGUI#446]
Hi,

I extracted the saltgui folder in "/srv/www/htdocs" and I was able to access the login page. I created the "saltuser" and place the following in "/etc/salt/master.d/saltgui.conf":
```
# Setup cherrypy
rest_cherrypy:
  port: 3333
  host: 127.0.0.1
  disable_ssl: true
  app: /srv/www/htdocs/saltgui/index.html
  static: /srv/www/htdocs/saltgui/static
  static_path: /static

# Setup API authentication
external_auth:
  pam:
    saltuser:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```
After that, I restarted the salt-master and salt-api then upon trying to login using "saltuser", it says "Authentication failed".
![image](https://user-images.githubusercontent.com/73015677/166104918-562e47f5-fab0-416b-846f-a2538644d342.png)

Did I miss something?
