### ISSUE TITLE
new page: schedule view

### ISSUE THREAD

**Issue by erwindon** [erwindon/SaltGUI#59]
SaltGUI currently has an overview of the minions and its keys. And pages with an overview of grains and an overview of pillars are already proposed/discussed.
A next proposed overview is the schedules that are installed on a minion.
Basic presentation is the same as for grains/pillars: the main screen shows the number of schedules present. When selecting a minion, the jobs panel is replaced by the overview of the schedules for the selected minion. The information returned is presented as-is, so as a piece of data.
Information is retrieved by operation `schedule.list`.
The following smoothing is performed on the data:
* the field `jid_include` is never shown
* the field `name` is never shown as a separate field, the entry already has the name
* the value `maxrunning: 1` is not shown
* the value `enabled: true` is not shown
* disabled schedules are displayed in gray

for api details see https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.schedule.html

The following functionality may be proposed separately in the future:
* displaying the scheduler status. it can be switched off completely, this is independent of the schedule/job status.
* commands to enable/disable jobs
* commands to enable/disable scheduler
* commands to delete a job
* commands to add/edit a job (visually difficult)

**Comment by erwindon** [comment]
SaltGUI currently has an overview of the minions and its keys. and pages with an overview of grains and an overview of pillars are underway.
a next proposed overview is the schedules that are installed on a minion.
basic presentation is the same as for grains/pillars: when selecting a minion, the jobs panel is replaced by the schedules overview for the selected minion.
information is retrieved by operation `schedule.list`. the information returned is presented as-is, so as a piece of data.
the following smoothing is performed on the data

**Comment by erwindon** [comment]
sample output from `schedule.list`:
```
    schedule:
      job1:
        enabled: false
        function: test.ping
        jid_include: true
        maxrunning: 1
        name: job1
        seconds: 60
      run_schedule:
        enabled: true
        function: state.highstate
        jid_include: true
        maxrunning: 1
        name: run_schedule
        seconds: 86400
        splay: 3600
```
